package cn.kgc.xiangqin.service;

import cn.kgc.xiangqin.entity.UserPass;
import cn.kgc.xiangqin.entity.UserPassExample;
import org.apache.ibatis.annotations.Param;
import org.springframework.security.core.userdetails.User;

import java.util.List;

/**
 * @Author: ZZY
 * @Date: 2020/8/8 16:13
 */

public interface UserPassService {

    Integer delete(@Param("uid") int uid);


    UserPass Login(UserPass userPass);
    List<UserPass>  queryAll(@Param("uid") int uid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_pass
     *
     * @mbg.generated Sat Aug 08 15:49:35 CST 2020
     */
    long countByExample(UserPassExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_pass
     *
     * @mbg.generated Sat Aug 08 15:49:35 CST 2020
     */
    int deleteByExample(UserPassExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_pass
     *
     * @mbg.generated Sat Aug 08 15:49:35 CST 2020
     */
    int deleteByPrimaryKey(String uname);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_pass
     *
     * @mbg.generated Sat Aug 08 15:49:35 CST 2020
     */
    int insert(UserPass record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_pass
     *
     * @mbg.generated Sat Aug 08 15:49:35 CST 2020
     */
    int insertSelective(UserPass record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_pass
     *
     * @mbg.generated Sat Aug 08 15:49:35 CST 2020
     */
    List<UserPass> selectByExample(UserPassExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_pass
     *
     * @mbg.generated Sat Aug 08 15:49:35 CST 2020
     */
    UserPass selectByPrimaryKey(String uname);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_pass
     *
     * @mbg.generated Sat Aug 08 15:49:35 CST 2020
     */
    int updateByExampleSelective(@Param("record") UserPass record, @Param("example") UserPassExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_pass
     *
     * @mbg.generated Sat Aug 08 15:49:35 CST 2020
     */
    int updateByExample(@Param("record") UserPass record, @Param("example") UserPassExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_pass
     *
     * @mbg.generated Sat Aug 08 15:49:35 CST 2020
     */
    int updateByPrimaryKeySelective(UserPass record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_pass
     *
     * @mbg.generated Sat Aug 08 15:49:35 CST 2020
     */
    int updateByPrimaryKey(UserPass record);

    /*登录*/
    public UserPass getNameAndPassword(String uname, String upassword);

    /*注册*/
    boolean register(String uname, String upassword);

    int findUserByLgName(String uname);



}
