package cn.kgc.xiangqin.entity;

public class HuoDong {
    public HuoDong() {
    }

    public HuoDong(Integer id, String name, String sex, String birth, String height, String education, String dwell, String work, Integer phone, Integer judge) {
        this.id = id;
        this.name = name;
        this.sex = sex;
        this.birth = birth;
        this.height = height;
        this.education = education;
        this.dwell = dwell;
        this.work = work;
        this.phone = phone;
        this.judge = judge;
    }

    @Override
    public String toString() {
        return "HuoDong{" +
                "id=" + id +
                ", name='" + name + '\'' +
                ", sex='" + sex + '\'' +
                ", birth='" + birth + '\'' +
                ", height='" + height + '\'' +
                ", education='" + education + '\'' +
                ", dwell='" + dwell + '\'' +
                ", work='" + work + '\'' +
                ", phone=" + phone +
                ", judge=" + judge +
                '}';
    }

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column huodong.id
     *
     * @mbg.generated Tue Aug 11 17:09:51 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column huodong.name
     *
     * @mbg.generated Tue Aug 11 17:09:51 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column huodong.sex
     *
     * @mbg.generated Tue Aug 11 17:09:51 CST 2020
     */
    private String sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column huodong.birth
     *
     * @mbg.generated Tue Aug 11 17:09:51 CST 2020
     */
    private String birth;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column huodong.height
     *
     * @mbg.generated Tue Aug 11 17:09:51 CST 2020
     */
    private String height;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column huodong.education
     *
     * @mbg.generated Tue Aug 11 17:09:51 CST 2020
     */
    private String education;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column huodong.dwell
     *
     * @mbg.generated Tue Aug 11 17:09:51 CST 2020
     */
    private String dwell;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column huodong.work
     *
     * @mbg.generated Tue Aug 11 17:09:51 CST 2020
     */
    private String work;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column huodong.phone
     *
     * @mbg.generated Tue Aug 11 17:09:51 CST 2020
     */
    private Integer phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column huodong.judge
     *
     * @mbg.generated Tue Aug 11 17:09:51 CST 2020
     */
    private Integer judge;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column huodong.id
     *
     * @return the value of huodong.id
     *
     * @mbg.generated Tue Aug 11 17:09:51 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column huodong.id
     *
     * @param id the value for huodong.id
     *
     * @mbg.generated Tue Aug 11 17:09:51 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column huodong.name
     *
     * @return the value of huodong.name
     *
     * @mbg.generated Tue Aug 11 17:09:51 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column huodong.name
     *
     * @param name the value for huodong.name
     *
     * @mbg.generated Tue Aug 11 17:09:51 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column huodong.sex
     *
     * @return the value of huodong.sex
     *
     * @mbg.generated Tue Aug 11 17:09:51 CST 2020
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column huodong.sex
     *
     * @param sex the value for huodong.sex
     *
     * @mbg.generated Tue Aug 11 17:09:51 CST 2020
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column huodong.birth
     *
     * @return the value of huodong.birth
     *
     * @mbg.generated Tue Aug 11 17:09:51 CST 2020
     */
    public String getBirth() {
        return birth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column huodong.birth
     *
     * @param birth the value for huodong.birth
     *
     * @mbg.generated Tue Aug 11 17:09:51 CST 2020
     */
    public void setBirth(String birth) {
        this.birth = birth == null ? null : birth.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column huodong.height
     *
     * @return the value of huodong.height
     *
     * @mbg.generated Tue Aug 11 17:09:51 CST 2020
     */
    public String getHeight() {
        return height;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column huodong.height
     *
     * @param height the value for huodong.height
     *
     * @mbg.generated Tue Aug 11 17:09:51 CST 2020
     */
    public void setHeight(String height) {
        this.height = height == null ? null : height.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column huodong.education
     *
     * @return the value of huodong.education
     *
     * @mbg.generated Tue Aug 11 17:09:51 CST 2020
     */
    public String getEducation() {
        return education;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column huodong.education
     *
     * @param education the value for huodong.education
     *
     * @mbg.generated Tue Aug 11 17:09:51 CST 2020
     */
    public void setEducation(String education) {
        this.education = education == null ? null : education.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column huodong.dwell
     *
     * @return the value of huodong.dwell
     *
     * @mbg.generated Tue Aug 11 17:09:51 CST 2020
     */
    public String getDwell() {
        return dwell;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column huodong.dwell
     *
     * @param dwell the value for huodong.dwell
     *
     * @mbg.generated Tue Aug 11 17:09:51 CST 2020
     */
    public void setDwell(String dwell) {
        this.dwell = dwell == null ? null : dwell.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column huodong.work
     *
     * @return the value of huodong.work
     *
     * @mbg.generated Tue Aug 11 17:09:51 CST 2020
     */
    public String getWork() {
        return work;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column huodong.work
     *
     * @param work the value for huodong.work
     *
     * @mbg.generated Tue Aug 11 17:09:51 CST 2020
     */
    public void setWork(String work) {
        this.work = work == null ? null : work.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column huodong.phone
     *
     * @return the value of huodong.phone
     *
     * @mbg.generated Tue Aug 11 17:09:51 CST 2020
     */
    public Integer getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column huodong.phone
     *
     * @param phone the value for huodong.phone
     *
     * @mbg.generated Tue Aug 11 17:09:51 CST 2020
     */
    public void setPhone(Integer phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column huodong.judge
     *
     * @return the value of huodong.judge
     *
     * @mbg.generated Tue Aug 11 17:09:51 CST 2020
     */
    public Integer getJudge() {
        return judge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column huodong.judge
     *
     * @param judge the value for huodong.judge
     *
     * @mbg.generated Tue Aug 11 17:09:51 CST 2020
     */
    public void setJudge(Integer judge) {
        this.judge = judge;
    }
}