package cn.kgc.xiangqin.entity;

import java.util.ArrayList;
import java.util.List;

public class MarriageExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table marriage
     *
     * @mbg.generated Tue Aug 11 17:06:47 CST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table marriage
     *
     * @mbg.generated Tue Aug 11 17:06:47 CST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table marriage
     *
     * @mbg.generated Tue Aug 11 17:06:47 CST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table marriage
     *
     * @mbg.generated Tue Aug 11 17:06:47 CST 2020
     */
    public MarriageExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table marriage
     *
     * @mbg.generated Tue Aug 11 17:06:47 CST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table marriage
     *
     * @mbg.generated Tue Aug 11 17:06:47 CST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table marriage
     *
     * @mbg.generated Tue Aug 11 17:06:47 CST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table marriage
     *
     * @mbg.generated Tue Aug 11 17:06:47 CST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table marriage
     *
     * @mbg.generated Tue Aug 11 17:06:47 CST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table marriage
     *
     * @mbg.generated Tue Aug 11 17:06:47 CST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table marriage
     *
     * @mbg.generated Tue Aug 11 17:06:47 CST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table marriage
     *
     * @mbg.generated Tue Aug 11 17:06:47 CST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table marriage
     *
     * @mbg.generated Tue Aug 11 17:06:47 CST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table marriage
     *
     * @mbg.generated Tue Aug 11 17:06:47 CST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table marriage
     *
     * @mbg.generated Tue Aug 11 17:06:47 CST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andKidIsNull() {
            addCriterion("kid is null");
            return (Criteria) this;
        }

        public Criteria andKidIsNotNull() {
            addCriterion("kid is not null");
            return (Criteria) this;
        }

        public Criteria andKidEqualTo(String value) {
            addCriterion("kid =", value, "kid");
            return (Criteria) this;
        }

        public Criteria andKidNotEqualTo(String value) {
            addCriterion("kid <>", value, "kid");
            return (Criteria) this;
        }

        public Criteria andKidGreaterThan(String value) {
            addCriterion("kid >", value, "kid");
            return (Criteria) this;
        }

        public Criteria andKidGreaterThanOrEqualTo(String value) {
            addCriterion("kid >=", value, "kid");
            return (Criteria) this;
        }

        public Criteria andKidLessThan(String value) {
            addCriterion("kid <", value, "kid");
            return (Criteria) this;
        }

        public Criteria andKidLessThanOrEqualTo(String value) {
            addCriterion("kid <=", value, "kid");
            return (Criteria) this;
        }

        public Criteria andKidLike(String value) {
            addCriterion("kid like", value, "kid");
            return (Criteria) this;
        }

        public Criteria andKidNotLike(String value) {
            addCriterion("kid not like", value, "kid");
            return (Criteria) this;
        }

        public Criteria andKidIn(List<String> values) {
            addCriterion("kid in", values, "kid");
            return (Criteria) this;
        }

        public Criteria andKidNotIn(List<String> values) {
            addCriterion("kid not in", values, "kid");
            return (Criteria) this;
        }

        public Criteria andKidBetween(String value1, String value2) {
            addCriterion("kid between", value1, value2, "kid");
            return (Criteria) this;
        }

        public Criteria andKidNotBetween(String value1, String value2) {
            addCriterion("kid not between", value1, value2, "kid");
            return (Criteria) this;
        }

        public Criteria andMarriedIsNull() {
            addCriterion("married is null");
            return (Criteria) this;
        }

        public Criteria andMarriedIsNotNull() {
            addCriterion("married is not null");
            return (Criteria) this;
        }

        public Criteria andMarriedEqualTo(String value) {
            addCriterion("married =", value, "married");
            return (Criteria) this;
        }

        public Criteria andMarriedNotEqualTo(String value) {
            addCriterion("married <>", value, "married");
            return (Criteria) this;
        }

        public Criteria andMarriedGreaterThan(String value) {
            addCriterion("married >", value, "married");
            return (Criteria) this;
        }

        public Criteria andMarriedGreaterThanOrEqualTo(String value) {
            addCriterion("married >=", value, "married");
            return (Criteria) this;
        }

        public Criteria andMarriedLessThan(String value) {
            addCriterion("married <", value, "married");
            return (Criteria) this;
        }

        public Criteria andMarriedLessThanOrEqualTo(String value) {
            addCriterion("married <=", value, "married");
            return (Criteria) this;
        }

        public Criteria andMarriedLike(String value) {
            addCriterion("married like", value, "married");
            return (Criteria) this;
        }

        public Criteria andMarriedNotLike(String value) {
            addCriterion("married not like", value, "married");
            return (Criteria) this;
        }

        public Criteria andMarriedIn(List<String> values) {
            addCriterion("married in", values, "married");
            return (Criteria) this;
        }

        public Criteria andMarriedNotIn(List<String> values) {
            addCriterion("married not in", values, "married");
            return (Criteria) this;
        }

        public Criteria andMarriedBetween(String value1, String value2) {
            addCriterion("married between", value1, value2, "married");
            return (Criteria) this;
        }

        public Criteria andMarriedNotBetween(String value1, String value2) {
            addCriterion("married not between", value1, value2, "married");
            return (Criteria) this;
        }

        public Criteria andCeaseIsNull() {
            addCriterion("cease is null");
            return (Criteria) this;
        }

        public Criteria andCeaseIsNotNull() {
            addCriterion("cease is not null");
            return (Criteria) this;
        }

        public Criteria andCeaseEqualTo(String value) {
            addCriterion("cease =", value, "cease");
            return (Criteria) this;
        }

        public Criteria andCeaseNotEqualTo(String value) {
            addCriterion("cease <>", value, "cease");
            return (Criteria) this;
        }

        public Criteria andCeaseGreaterThan(String value) {
            addCriterion("cease >", value, "cease");
            return (Criteria) this;
        }

        public Criteria andCeaseGreaterThanOrEqualTo(String value) {
            addCriterion("cease >=", value, "cease");
            return (Criteria) this;
        }

        public Criteria andCeaseLessThan(String value) {
            addCriterion("cease <", value, "cease");
            return (Criteria) this;
        }

        public Criteria andCeaseLessThanOrEqualTo(String value) {
            addCriterion("cease <=", value, "cease");
            return (Criteria) this;
        }

        public Criteria andCeaseLike(String value) {
            addCriterion("cease like", value, "cease");
            return (Criteria) this;
        }

        public Criteria andCeaseNotLike(String value) {
            addCriterion("cease not like", value, "cease");
            return (Criteria) this;
        }

        public Criteria andCeaseIn(List<String> values) {
            addCriterion("cease in", values, "cease");
            return (Criteria) this;
        }

        public Criteria andCeaseNotIn(List<String> values) {
            addCriterion("cease not in", values, "cease");
            return (Criteria) this;
        }

        public Criteria andCeaseBetween(String value1, String value2) {
            addCriterion("cease between", value1, value2, "cease");
            return (Criteria) this;
        }

        public Criteria andCeaseNotBetween(String value1, String value2) {
            addCriterion("cease not between", value1, value2, "cease");
            return (Criteria) this;
        }

        public Criteria andSeniorityIsNull() {
            addCriterion("seniority is null");
            return (Criteria) this;
        }

        public Criteria andSeniorityIsNotNull() {
            addCriterion("seniority is not null");
            return (Criteria) this;
        }

        public Criteria andSeniorityEqualTo(String value) {
            addCriterion("seniority =", value, "seniority");
            return (Criteria) this;
        }

        public Criteria andSeniorityNotEqualTo(String value) {
            addCriterion("seniority <>", value, "seniority");
            return (Criteria) this;
        }

        public Criteria andSeniorityGreaterThan(String value) {
            addCriterion("seniority >", value, "seniority");
            return (Criteria) this;
        }

        public Criteria andSeniorityGreaterThanOrEqualTo(String value) {
            addCriterion("seniority >=", value, "seniority");
            return (Criteria) this;
        }

        public Criteria andSeniorityLessThan(String value) {
            addCriterion("seniority <", value, "seniority");
            return (Criteria) this;
        }

        public Criteria andSeniorityLessThanOrEqualTo(String value) {
            addCriterion("seniority <=", value, "seniority");
            return (Criteria) this;
        }

        public Criteria andSeniorityLike(String value) {
            addCriterion("seniority like", value, "seniority");
            return (Criteria) this;
        }

        public Criteria andSeniorityNotLike(String value) {
            addCriterion("seniority not like", value, "seniority");
            return (Criteria) this;
        }

        public Criteria andSeniorityIn(List<String> values) {
            addCriterion("seniority in", values, "seniority");
            return (Criteria) this;
        }

        public Criteria andSeniorityNotIn(List<String> values) {
            addCriterion("seniority not in", values, "seniority");
            return (Criteria) this;
        }

        public Criteria andSeniorityBetween(String value1, String value2) {
            addCriterion("seniority between", value1, value2, "seniority");
            return (Criteria) this;
        }

        public Criteria andSeniorityNotBetween(String value1, String value2) {
            addCriterion("seniority not between", value1, value2, "seniority");
            return (Criteria) this;
        }

        public Criteria andConditionIsNull() {
            addCriterion("condition is null");
            return (Criteria) this;
        }

        public Criteria andConditionIsNotNull() {
            addCriterion("condition is not null");
            return (Criteria) this;
        }

        public Criteria andConditionEqualTo(String value) {
            addCriterion("condition =", value, "condition");
            return (Criteria) this;
        }

        public Criteria andConditionNotEqualTo(String value) {
            addCriterion("condition <>", value, "condition");
            return (Criteria) this;
        }

        public Criteria andConditionGreaterThan(String value) {
            addCriterion("condition >", value, "condition");
            return (Criteria) this;
        }

        public Criteria andConditionGreaterThanOrEqualTo(String value) {
            addCriterion("condition >=", value, "condition");
            return (Criteria) this;
        }

        public Criteria andConditionLessThan(String value) {
            addCriterion("condition <", value, "condition");
            return (Criteria) this;
        }

        public Criteria andConditionLessThanOrEqualTo(String value) {
            addCriterion("condition <=", value, "condition");
            return (Criteria) this;
        }

        public Criteria andConditionLike(String value) {
            addCriterion("condition like", value, "condition");
            return (Criteria) this;
        }

        public Criteria andConditionNotLike(String value) {
            addCriterion("condition not like", value, "condition");
            return (Criteria) this;
        }

        public Criteria andConditionIn(List<String> values) {
            addCriterion("condition in", values, "condition");
            return (Criteria) this;
        }

        public Criteria andConditionNotIn(List<String> values) {
            addCriterion("condition not in", values, "condition");
            return (Criteria) this;
        }

        public Criteria andConditionBetween(String value1, String value2) {
            addCriterion("condition between", value1, value2, "condition");
            return (Criteria) this;
        }

        public Criteria andConditionNotBetween(String value1, String value2) {
            addCriterion("condition not between", value1, value2, "condition");
            return (Criteria) this;
        }

        public Criteria andSisterIsNull() {
            addCriterion("sister is null");
            return (Criteria) this;
        }

        public Criteria andSisterIsNotNull() {
            addCriterion("sister is not null");
            return (Criteria) this;
        }

        public Criteria andSisterEqualTo(String value) {
            addCriterion("sister =", value, "sister");
            return (Criteria) this;
        }

        public Criteria andSisterNotEqualTo(String value) {
            addCriterion("sister <>", value, "sister");
            return (Criteria) this;
        }

        public Criteria andSisterGreaterThan(String value) {
            addCriterion("sister >", value, "sister");
            return (Criteria) this;
        }

        public Criteria andSisterGreaterThanOrEqualTo(String value) {
            addCriterion("sister >=", value, "sister");
            return (Criteria) this;
        }

        public Criteria andSisterLessThan(String value) {
            addCriterion("sister <", value, "sister");
            return (Criteria) this;
        }

        public Criteria andSisterLessThanOrEqualTo(String value) {
            addCriterion("sister <=", value, "sister");
            return (Criteria) this;
        }

        public Criteria andSisterLike(String value) {
            addCriterion("sister like", value, "sister");
            return (Criteria) this;
        }

        public Criteria andSisterNotLike(String value) {
            addCriterion("sister not like", value, "sister");
            return (Criteria) this;
        }

        public Criteria andSisterIn(List<String> values) {
            addCriterion("sister in", values, "sister");
            return (Criteria) this;
        }

        public Criteria andSisterNotIn(List<String> values) {
            addCriterion("sister not in", values, "sister");
            return (Criteria) this;
        }

        public Criteria andSisterBetween(String value1, String value2) {
            addCriterion("sister between", value1, value2, "sister");
            return (Criteria) this;
        }

        public Criteria andSisterNotBetween(String value1, String value2) {
            addCriterion("sister not between", value1, value2, "sister");
            return (Criteria) this;
        }

        public Criteria andEconomicsIsNull() {
            addCriterion("economics is null");
            return (Criteria) this;
        }

        public Criteria andEconomicsIsNotNull() {
            addCriterion("economics is not null");
            return (Criteria) this;
        }

        public Criteria andEconomicsEqualTo(String value) {
            addCriterion("economics =", value, "economics");
            return (Criteria) this;
        }

        public Criteria andEconomicsNotEqualTo(String value) {
            addCriterion("economics <>", value, "economics");
            return (Criteria) this;
        }

        public Criteria andEconomicsGreaterThan(String value) {
            addCriterion("economics >", value, "economics");
            return (Criteria) this;
        }

        public Criteria andEconomicsGreaterThanOrEqualTo(String value) {
            addCriterion("economics >=", value, "economics");
            return (Criteria) this;
        }

        public Criteria andEconomicsLessThan(String value) {
            addCriterion("economics <", value, "economics");
            return (Criteria) this;
        }

        public Criteria andEconomicsLessThanOrEqualTo(String value) {
            addCriterion("economics <=", value, "economics");
            return (Criteria) this;
        }

        public Criteria andEconomicsLike(String value) {
            addCriterion("economics like", value, "economics");
            return (Criteria) this;
        }

        public Criteria andEconomicsNotLike(String value) {
            addCriterion("economics not like", value, "economics");
            return (Criteria) this;
        }

        public Criteria andEconomicsIn(List<String> values) {
            addCriterion("economics in", values, "economics");
            return (Criteria) this;
        }

        public Criteria andEconomicsNotIn(List<String> values) {
            addCriterion("economics not in", values, "economics");
            return (Criteria) this;
        }

        public Criteria andEconomicsBetween(String value1, String value2) {
            addCriterion("economics between", value1, value2, "economics");
            return (Criteria) this;
        }

        public Criteria andEconomicsNotBetween(String value1, String value2) {
            addCriterion("economics not between", value1, value2, "economics");
            return (Criteria) this;
        }

        public Criteria andHealthIsNull() {
            addCriterion("health is null");
            return (Criteria) this;
        }

        public Criteria andHealthIsNotNull() {
            addCriterion("health is not null");
            return (Criteria) this;
        }

        public Criteria andHealthEqualTo(String value) {
            addCriterion("health =", value, "health");
            return (Criteria) this;
        }

        public Criteria andHealthNotEqualTo(String value) {
            addCriterion("health <>", value, "health");
            return (Criteria) this;
        }

        public Criteria andHealthGreaterThan(String value) {
            addCriterion("health >", value, "health");
            return (Criteria) this;
        }

        public Criteria andHealthGreaterThanOrEqualTo(String value) {
            addCriterion("health >=", value, "health");
            return (Criteria) this;
        }

        public Criteria andHealthLessThan(String value) {
            addCriterion("health <", value, "health");
            return (Criteria) this;
        }

        public Criteria andHealthLessThanOrEqualTo(String value) {
            addCriterion("health <=", value, "health");
            return (Criteria) this;
        }

        public Criteria andHealthLike(String value) {
            addCriterion("health like", value, "health");
            return (Criteria) this;
        }

        public Criteria andHealthNotLike(String value) {
            addCriterion("health not like", value, "health");
            return (Criteria) this;
        }

        public Criteria andHealthIn(List<String> values) {
            addCriterion("health in", values, "health");
            return (Criteria) this;
        }

        public Criteria andHealthNotIn(List<String> values) {
            addCriterion("health not in", values, "health");
            return (Criteria) this;
        }

        public Criteria andHealthBetween(String value1, String value2) {
            addCriterion("health between", value1, value2, "health");
            return (Criteria) this;
        }

        public Criteria andHealthNotBetween(String value1, String value2) {
            addCriterion("health not between", value1, value2, "health");
            return (Criteria) this;
        }

        public Criteria andIntroIsNull() {
            addCriterion("intro is null");
            return (Criteria) this;
        }

        public Criteria andIntroIsNotNull() {
            addCriterion("intro is not null");
            return (Criteria) this;
        }

        public Criteria andIntroEqualTo(String value) {
            addCriterion("intro =", value, "intro");
            return (Criteria) this;
        }

        public Criteria andIntroNotEqualTo(String value) {
            addCriterion("intro <>", value, "intro");
            return (Criteria) this;
        }

        public Criteria andIntroGreaterThan(String value) {
            addCriterion("intro >", value, "intro");
            return (Criteria) this;
        }

        public Criteria andIntroGreaterThanOrEqualTo(String value) {
            addCriterion("intro >=", value, "intro");
            return (Criteria) this;
        }

        public Criteria andIntroLessThan(String value) {
            addCriterion("intro <", value, "intro");
            return (Criteria) this;
        }

        public Criteria andIntroLessThanOrEqualTo(String value) {
            addCriterion("intro <=", value, "intro");
            return (Criteria) this;
        }

        public Criteria andIntroLike(String value) {
            addCriterion("intro like", value, "intro");
            return (Criteria) this;
        }

        public Criteria andIntroNotLike(String value) {
            addCriterion("intro not like", value, "intro");
            return (Criteria) this;
        }

        public Criteria andIntroIn(List<String> values) {
            addCriterion("intro in", values, "intro");
            return (Criteria) this;
        }

        public Criteria andIntroNotIn(List<String> values) {
            addCriterion("intro not in", values, "intro");
            return (Criteria) this;
        }

        public Criteria andIntroBetween(String value1, String value2) {
            addCriterion("intro between", value1, value2, "intro");
            return (Criteria) this;
        }

        public Criteria andIntroNotBetween(String value1, String value2) {
            addCriterion("intro not between", value1, value2, "intro");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table marriage
     *
     * @mbg.generated do_not_delete_during_merge Tue Aug 11 17:06:47 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table marriage
     *
     * @mbg.generated Tue Aug 11 17:06:47 CST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}