package cn.kgc.xiangqin.entity;

public class Marriage {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column marriage.id
     *
     * @mbg.generated Tue Aug 11 17:06:47 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column marriage.kid
     *
     * @mbg.generated Tue Aug 11 17:06:47 CST 2020
     */
    private String kid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column marriage.married
     *
     * @mbg.generated Tue Aug 11 17:06:47 CST 2020
     */
    private String married;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column marriage.cease
     *
     * @mbg.generated Tue Aug 11 17:06:47 CST 2020
     */
    private String cease;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column marriage.seniority
     *
     * @mbg.generated Tue Aug 11 17:06:47 CST 2020
     */
    private String seniority;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column marriage.condition
     *
     * @mbg.generated Tue Aug 11 17:06:47 CST 2020
     */
    private String condition;

    @Override
    public String toString() {
        return "Marriage{" +
                "id=" + id +
                ", kid='" + kid + '\'' +
                ", married='" + married + '\'' +
                ", cease='" + cease + '\'' +
                ", seniority='" + seniority + '\'' +
                ", condition='" + condition + '\'' +
                ", sister='" + sister + '\'' +
                ", economics='" + economics + '\'' +
                ", health='" + health + '\'' +
                ", intro='" + intro + '\'' +
                '}';
    }

    public Marriage() {
    }

    public Marriage(Integer id, String kid, String married, String cease, String seniority, String condition, String sister, String economics, String health, String intro) {
        this.id = id;
        this.kid = kid;
        this.married = married;
        this.cease = cease;
        this.seniority = seniority;
        this.condition = condition;
        this.sister = sister;
        this.economics = economics;
        this.health = health;
        this.intro = intro;
    }

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column marriage.sister
     *
     * @mbg.generated Tue Aug 11 17:06:47 CST 2020
     */
    private String sister;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column marriage.economics
     *
     * @mbg.generated Tue Aug 11 17:06:47 CST 2020
     */
    private String economics;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column marriage.health
     *
     * @mbg.generated Tue Aug 11 17:06:47 CST 2020
     */
    private String health;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column marriage.intro
     *
     * @mbg.generated Tue Aug 11 17:06:47 CST 2020
     */
    private String intro;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column marriage.id
     *
     * @return the value of marriage.id
     *
     * @mbg.generated Tue Aug 11 17:06:47 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column marriage.id
     *
     * @param id the value for marriage.id
     *
     * @mbg.generated Tue Aug 11 17:06:47 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column marriage.kid
     *
     * @return the value of marriage.kid
     *
     * @mbg.generated Tue Aug 11 17:06:47 CST 2020
     */
    public String getKid() {
        return kid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column marriage.kid
     *
     * @param kid the value for marriage.kid
     *
     * @mbg.generated Tue Aug 11 17:06:47 CST 2020
     */
    public void setKid(String kid) {
        this.kid = kid == null ? null : kid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column marriage.married
     *
     * @return the value of marriage.married
     *
     * @mbg.generated Tue Aug 11 17:06:47 CST 2020
     */
    public String getMarried() {
        return married;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column marriage.married
     *
     * @param married the value for marriage.married
     *
     * @mbg.generated Tue Aug 11 17:06:47 CST 2020
     */
    public void setMarried(String married) {
        this.married = married == null ? null : married.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column marriage.cease
     *
     * @return the value of marriage.cease
     *
     * @mbg.generated Tue Aug 11 17:06:47 CST 2020
     */
    public String getCease() {
        return cease;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column marriage.cease
     *
     * @param cease the value for marriage.cease
     *
     * @mbg.generated Tue Aug 11 17:06:47 CST 2020
     */
    public void setCease(String cease) {
        this.cease = cease == null ? null : cease.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column marriage.seniority
     *
     * @return the value of marriage.seniority
     *
     * @mbg.generated Tue Aug 11 17:06:47 CST 2020
     */
    public String getSeniority() {
        return seniority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column marriage.seniority
     *
     * @param seniority the value for marriage.seniority
     *
     * @mbg.generated Tue Aug 11 17:06:47 CST 2020
     */
    public void setSeniority(String seniority) {
        this.seniority = seniority == null ? null : seniority.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column marriage.condition
     *
     * @return the value of marriage.condition
     *
     * @mbg.generated Tue Aug 11 17:06:47 CST 2020
     */
    public String getCondition() {
        return condition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column marriage.condition
     *
     * @param condition the value for marriage.condition
     *
     * @mbg.generated Tue Aug 11 17:06:47 CST 2020
     */
    public void setCondition(String condition) {
        this.condition = condition == null ? null : condition.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column marriage.sister
     *
     * @return the value of marriage.sister
     *
     * @mbg.generated Tue Aug 11 17:06:47 CST 2020
     */
    public String getSister() {
        return sister;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column marriage.sister
     *
     * @param sister the value for marriage.sister
     *
     * @mbg.generated Tue Aug 11 17:06:47 CST 2020
     */
    public void setSister(String sister) {
        this.sister = sister == null ? null : sister.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column marriage.economics
     *
     * @return the value of marriage.economics
     *
     * @mbg.generated Tue Aug 11 17:06:47 CST 2020
     */
    public String getEconomics() {
        return economics;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column marriage.economics
     *
     * @param economics the value for marriage.economics
     *
     * @mbg.generated Tue Aug 11 17:06:47 CST 2020
     */
    public void setEconomics(String economics) {
        this.economics = economics == null ? null : economics.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column marriage.health
     *
     * @return the value of marriage.health
     *
     * @mbg.generated Tue Aug 11 17:06:47 CST 2020
     */
    public String getHealth() {
        return health;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column marriage.health
     *
     * @param health the value for marriage.health
     *
     * @mbg.generated Tue Aug 11 17:06:47 CST 2020
     */
    public void setHealth(String health) {
        this.health = health == null ? null : health.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column marriage.intro
     *
     * @return the value of marriage.intro
     *
     * @mbg.generated Tue Aug 11 17:06:47 CST 2020
     */
    public String getIntro() {
        return intro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column marriage.intro
     *
     * @param intro the value for marriage.intro
     *
     * @mbg.generated Tue Aug 11 17:06:47 CST 2020
     */
    public void setIntro(String intro) {
        this.intro = intro == null ? null : intro.trim();
    }
}