package cn.kgc.xiangqin.entity;

public class ShengHuo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shenghuo.id
     *
     * @mbg.generated Tue Aug 11 17:10:26 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shenghuo.xiyan
     *
     * @mbg.generated Tue Aug 11 17:10:26 CST 2020
     */
    private String xiyan;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shenghuo.yinjiu
     *
     * @mbg.generated Tue Aug 11 17:10:26 CST 2020
     */
    private String yinjiu;

    @Override
    public String toString() {
        return "ShengHuo{" +
                "id=" + id +
                ", xiyan='" + xiyan + '\'' +
                ", yinjiu='" + yinjiu + '\'' +
                ", jianshen='" + jianshen + '\'' +
                ", eat='" + eat + '\'' +
                ", buy='" + buy + '\'' +
                ", religion='" + religion + '\'' +
                ", time='" + time + '\'' +
                ", pet='" + pet + '\'' +
                '}';
    }

    public ShengHuo() {
    }

    public ShengHuo(Integer id, String xiyan, String yinjiu, String jianshen, String eat, String buy, String religion, String time, String pet) {
        this.id = id;
        this.xiyan = xiyan;
        this.yinjiu = yinjiu;
        this.jianshen = jianshen;
        this.eat = eat;
        this.buy = buy;
        this.religion = religion;
        this.time = time;
        this.pet = pet;
    }

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shenghuo.jianshen
     *
     * @mbg.generated Tue Aug 11 17:10:26 CST 2020
     */
    private String jianshen;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shenghuo.eat
     *
     * @mbg.generated Tue Aug 11 17:10:26 CST 2020
     */
    private String eat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shenghuo.buy
     *
     * @mbg.generated Tue Aug 11 17:10:26 CST 2020
     */
    private String buy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shenghuo.religion
     *
     * @mbg.generated Tue Aug 11 17:10:26 CST 2020
     */
    private String religion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shenghuo.time
     *
     * @mbg.generated Tue Aug 11 17:10:26 CST 2020
     */
    private String time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shenghuo.pet
     *
     * @mbg.generated Tue Aug 11 17:10:26 CST 2020
     */
    private String pet;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shenghuo.id
     *
     * @return the value of shenghuo.id
     *
     * @mbg.generated Tue Aug 11 17:10:26 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shenghuo.id
     *
     * @param id the value for shenghuo.id
     *
     * @mbg.generated Tue Aug 11 17:10:26 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shenghuo.xiyan
     *
     * @return the value of shenghuo.xiyan
     *
     * @mbg.generated Tue Aug 11 17:10:26 CST 2020
     */
    public String getXiyan() {
        return xiyan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shenghuo.xiyan
     *
     * @param xiyan the value for shenghuo.xiyan
     *
     * @mbg.generated Tue Aug 11 17:10:26 CST 2020
     */
    public void setXiyan(String xiyan) {
        this.xiyan = xiyan == null ? null : xiyan.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shenghuo.yinjiu
     *
     * @return the value of shenghuo.yinjiu
     *
     * @mbg.generated Tue Aug 11 17:10:26 CST 2020
     */
    public String getYinjiu() {
        return yinjiu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shenghuo.yinjiu
     *
     * @param yinjiu the value for shenghuo.yinjiu
     *
     * @mbg.generated Tue Aug 11 17:10:26 CST 2020
     */
    public void setYinjiu(String yinjiu) {
        this.yinjiu = yinjiu == null ? null : yinjiu.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shenghuo.jianshen
     *
     * @return the value of shenghuo.jianshen
     *
     * @mbg.generated Tue Aug 11 17:10:26 CST 2020
     */
    public String getJianshen() {
        return jianshen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shenghuo.jianshen
     *
     * @param jianshen the value for shenghuo.jianshen
     *
     * @mbg.generated Tue Aug 11 17:10:26 CST 2020
     */
    public void setJianshen(String jianshen) {
        this.jianshen = jianshen == null ? null : jianshen.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shenghuo.eat
     *
     * @return the value of shenghuo.eat
     *
     * @mbg.generated Tue Aug 11 17:10:26 CST 2020
     */
    public String getEat() {
        return eat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shenghuo.eat
     *
     * @param eat the value for shenghuo.eat
     *
     * @mbg.generated Tue Aug 11 17:10:26 CST 2020
     */
    public void setEat(String eat) {
        this.eat = eat == null ? null : eat.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shenghuo.buy
     *
     * @return the value of shenghuo.buy
     *
     * @mbg.generated Tue Aug 11 17:10:26 CST 2020
     */
    public String getBuy() {
        return buy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shenghuo.buy
     *
     * @param buy the value for shenghuo.buy
     *
     * @mbg.generated Tue Aug 11 17:10:26 CST 2020
     */
    public void setBuy(String buy) {
        this.buy = buy == null ? null : buy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shenghuo.religion
     *
     * @return the value of shenghuo.religion
     *
     * @mbg.generated Tue Aug 11 17:10:26 CST 2020
     */
    public String getReligion() {
        return religion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shenghuo.religion
     *
     * @param religion the value for shenghuo.religion
     *
     * @mbg.generated Tue Aug 11 17:10:26 CST 2020
     */
    public void setReligion(String religion) {
        this.religion = religion == null ? null : religion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shenghuo.time
     *
     * @return the value of shenghuo.time
     *
     * @mbg.generated Tue Aug 11 17:10:26 CST 2020
     */
    public String getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shenghuo.time
     *
     * @param time the value for shenghuo.time
     *
     * @mbg.generated Tue Aug 11 17:10:26 CST 2020
     */
    public void setTime(String time) {
        this.time = time == null ? null : time.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shenghuo.pet
     *
     * @return the value of shenghuo.pet
     *
     * @mbg.generated Tue Aug 11 17:10:26 CST 2020
     */
    public String getPet() {
        return pet;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shenghuo.pet
     *
     * @param pet the value for shenghuo.pet
     *
     * @mbg.generated Tue Aug 11 17:10:26 CST 2020
     */
    public void setPet(String pet) {
        this.pet = pet == null ? null : pet.trim();
    }
}