package cn.kgc.xiangqin.entity;

import java.util.ArrayList;
import java.util.List;

public class ShengHuoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table shenghuofanngshi
     *
     * @mbg.generated Tue Aug 11 10:35:40 CST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table shenghuofanngshi
     *
     * @mbg.generated Tue Aug 11 10:35:40 CST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table shenghuofanngshi
     *
     * @mbg.generated Tue Aug 11 10:35:40 CST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shenghuofanngshi
     *
     * @mbg.generated Tue Aug 11 10:35:40 CST 2020
     */
    public ShengHuoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shenghuofanngshi
     *
     * @mbg.generated Tue Aug 11 10:35:40 CST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shenghuofanngshi
     *
     * @mbg.generated Tue Aug 11 10:35:40 CST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shenghuofanngshi
     *
     * @mbg.generated Tue Aug 11 10:35:40 CST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shenghuofanngshi
     *
     * @mbg.generated Tue Aug 11 10:35:40 CST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shenghuofanngshi
     *
     * @mbg.generated Tue Aug 11 10:35:40 CST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shenghuofanngshi
     *
     * @mbg.generated Tue Aug 11 10:35:40 CST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shenghuofanngshi
     *
     * @mbg.generated Tue Aug 11 10:35:40 CST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shenghuofanngshi
     *
     * @mbg.generated Tue Aug 11 10:35:40 CST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shenghuofanngshi
     *
     * @mbg.generated Tue Aug 11 10:35:40 CST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shenghuofanngshi
     *
     * @mbg.generated Tue Aug 11 10:35:40 CST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table shenghuofanngshi
     *
     * @mbg.generated Tue Aug 11 10:35:40 CST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andXiyanIsNull() {
            addCriterion("xiyan is null");
            return (Criteria) this;
        }

        public Criteria andXiyanIsNotNull() {
            addCriterion("xiyan is not null");
            return (Criteria) this;
        }

        public Criteria andXiyanEqualTo(String value) {
            addCriterion("xiyan =", value, "xiyan");
            return (Criteria) this;
        }

        public Criteria andXiyanNotEqualTo(String value) {
            addCriterion("xiyan <>", value, "xiyan");
            return (Criteria) this;
        }

        public Criteria andXiyanGreaterThan(String value) {
            addCriterion("xiyan >", value, "xiyan");
            return (Criteria) this;
        }

        public Criteria andXiyanGreaterThanOrEqualTo(String value) {
            addCriterion("xiyan >=", value, "xiyan");
            return (Criteria) this;
        }

        public Criteria andXiyanLessThan(String value) {
            addCriterion("xiyan <", value, "xiyan");
            return (Criteria) this;
        }

        public Criteria andXiyanLessThanOrEqualTo(String value) {
            addCriterion("xiyan <=", value, "xiyan");
            return (Criteria) this;
        }

        public Criteria andXiyanLike(String value) {
            addCriterion("xiyan like", value, "xiyan");
            return (Criteria) this;
        }

        public Criteria andXiyanNotLike(String value) {
            addCriterion("xiyan not like", value, "xiyan");
            return (Criteria) this;
        }

        public Criteria andXiyanIn(List<String> values) {
            addCriterion("xiyan in", values, "xiyan");
            return (Criteria) this;
        }

        public Criteria andXiyanNotIn(List<String> values) {
            addCriterion("xiyan not in", values, "xiyan");
            return (Criteria) this;
        }

        public Criteria andXiyanBetween(String value1, String value2) {
            addCriterion("xiyan between", value1, value2, "xiyan");
            return (Criteria) this;
        }

        public Criteria andXiyanNotBetween(String value1, String value2) {
            addCriterion("xiyan not between", value1, value2, "xiyan");
            return (Criteria) this;
        }

        public Criteria andYinjiuIsNull() {
            addCriterion("yinjiu is null");
            return (Criteria) this;
        }

        public Criteria andYinjiuIsNotNull() {
            addCriterion("yinjiu is not null");
            return (Criteria) this;
        }

        public Criteria andYinjiuEqualTo(String value) {
            addCriterion("yinjiu =", value, "yinjiu");
            return (Criteria) this;
        }

        public Criteria andYinjiuNotEqualTo(String value) {
            addCriterion("yinjiu <>", value, "yinjiu");
            return (Criteria) this;
        }

        public Criteria andYinjiuGreaterThan(String value) {
            addCriterion("yinjiu >", value, "yinjiu");
            return (Criteria) this;
        }

        public Criteria andYinjiuGreaterThanOrEqualTo(String value) {
            addCriterion("yinjiu >=", value, "yinjiu");
            return (Criteria) this;
        }

        public Criteria andYinjiuLessThan(String value) {
            addCriterion("yinjiu <", value, "yinjiu");
            return (Criteria) this;
        }

        public Criteria andYinjiuLessThanOrEqualTo(String value) {
            addCriterion("yinjiu <=", value, "yinjiu");
            return (Criteria) this;
        }

        public Criteria andYinjiuLike(String value) {
            addCriterion("yinjiu like", value, "yinjiu");
            return (Criteria) this;
        }

        public Criteria andYinjiuNotLike(String value) {
            addCriterion("yinjiu not like", value, "yinjiu");
            return (Criteria) this;
        }

        public Criteria andYinjiuIn(List<String> values) {
            addCriterion("yinjiu in", values, "yinjiu");
            return (Criteria) this;
        }

        public Criteria andYinjiuNotIn(List<String> values) {
            addCriterion("yinjiu not in", values, "yinjiu");
            return (Criteria) this;
        }

        public Criteria andYinjiuBetween(String value1, String value2) {
            addCriterion("yinjiu between", value1, value2, "yinjiu");
            return (Criteria) this;
        }

        public Criteria andYinjiuNotBetween(String value1, String value2) {
            addCriterion("yinjiu not between", value1, value2, "yinjiu");
            return (Criteria) this;
        }

        public Criteria andJianshenIsNull() {
            addCriterion("jianshen is null");
            return (Criteria) this;
        }

        public Criteria andJianshenIsNotNull() {
            addCriterion("jianshen is not null");
            return (Criteria) this;
        }

        public Criteria andJianshenEqualTo(String value) {
            addCriterion("jianshen =", value, "jianshen");
            return (Criteria) this;
        }

        public Criteria andJianshenNotEqualTo(String value) {
            addCriterion("jianshen <>", value, "jianshen");
            return (Criteria) this;
        }

        public Criteria andJianshenGreaterThan(String value) {
            addCriterion("jianshen >", value, "jianshen");
            return (Criteria) this;
        }

        public Criteria andJianshenGreaterThanOrEqualTo(String value) {
            addCriterion("jianshen >=", value, "jianshen");
            return (Criteria) this;
        }

        public Criteria andJianshenLessThan(String value) {
            addCriterion("jianshen <", value, "jianshen");
            return (Criteria) this;
        }

        public Criteria andJianshenLessThanOrEqualTo(String value) {
            addCriterion("jianshen <=", value, "jianshen");
            return (Criteria) this;
        }

        public Criteria andJianshenLike(String value) {
            addCriterion("jianshen like", value, "jianshen");
            return (Criteria) this;
        }

        public Criteria andJianshenNotLike(String value) {
            addCriterion("jianshen not like", value, "jianshen");
            return (Criteria) this;
        }

        public Criteria andJianshenIn(List<String> values) {
            addCriterion("jianshen in", values, "jianshen");
            return (Criteria) this;
        }

        public Criteria andJianshenNotIn(List<String> values) {
            addCriterion("jianshen not in", values, "jianshen");
            return (Criteria) this;
        }

        public Criteria andJianshenBetween(String value1, String value2) {
            addCriterion("jianshen between", value1, value2, "jianshen");
            return (Criteria) this;
        }

        public Criteria andJianshenNotBetween(String value1, String value2) {
            addCriterion("jianshen not between", value1, value2, "jianshen");
            return (Criteria) this;
        }

        public Criteria andEatIsNull() {
            addCriterion("eat is null");
            return (Criteria) this;
        }

        public Criteria andEatIsNotNull() {
            addCriterion("eat is not null");
            return (Criteria) this;
        }

        public Criteria andEatEqualTo(String value) {
            addCriterion("eat =", value, "eat");
            return (Criteria) this;
        }

        public Criteria andEatNotEqualTo(String value) {
            addCriterion("eat <>", value, "eat");
            return (Criteria) this;
        }

        public Criteria andEatGreaterThan(String value) {
            addCriterion("eat >", value, "eat");
            return (Criteria) this;
        }

        public Criteria andEatGreaterThanOrEqualTo(String value) {
            addCriterion("eat >=", value, "eat");
            return (Criteria) this;
        }

        public Criteria andEatLessThan(String value) {
            addCriterion("eat <", value, "eat");
            return (Criteria) this;
        }

        public Criteria andEatLessThanOrEqualTo(String value) {
            addCriterion("eat <=", value, "eat");
            return (Criteria) this;
        }

        public Criteria andEatLike(String value) {
            addCriterion("eat like", value, "eat");
            return (Criteria) this;
        }

        public Criteria andEatNotLike(String value) {
            addCriterion("eat not like", value, "eat");
            return (Criteria) this;
        }

        public Criteria andEatIn(List<String> values) {
            addCriterion("eat in", values, "eat");
            return (Criteria) this;
        }

        public Criteria andEatNotIn(List<String> values) {
            addCriterion("eat not in", values, "eat");
            return (Criteria) this;
        }

        public Criteria andEatBetween(String value1, String value2) {
            addCriterion("eat between", value1, value2, "eat");
            return (Criteria) this;
        }

        public Criteria andEatNotBetween(String value1, String value2) {
            addCriterion("eat not between", value1, value2, "eat");
            return (Criteria) this;
        }

        public Criteria andBuyIsNull() {
            addCriterion("buy is null");
            return (Criteria) this;
        }

        public Criteria andBuyIsNotNull() {
            addCriterion("buy is not null");
            return (Criteria) this;
        }

        public Criteria andBuyEqualTo(String value) {
            addCriterion("buy =", value, "buy");
            return (Criteria) this;
        }

        public Criteria andBuyNotEqualTo(String value) {
            addCriterion("buy <>", value, "buy");
            return (Criteria) this;
        }

        public Criteria andBuyGreaterThan(String value) {
            addCriterion("buy >", value, "buy");
            return (Criteria) this;
        }

        public Criteria andBuyGreaterThanOrEqualTo(String value) {
            addCriterion("buy >=", value, "buy");
            return (Criteria) this;
        }

        public Criteria andBuyLessThan(String value) {
            addCriterion("buy <", value, "buy");
            return (Criteria) this;
        }

        public Criteria andBuyLessThanOrEqualTo(String value) {
            addCriterion("buy <=", value, "buy");
            return (Criteria) this;
        }

        public Criteria andBuyLike(String value) {
            addCriterion("buy like", value, "buy");
            return (Criteria) this;
        }

        public Criteria andBuyNotLike(String value) {
            addCriterion("buy not like", value, "buy");
            return (Criteria) this;
        }

        public Criteria andBuyIn(List<String> values) {
            addCriterion("buy in", values, "buy");
            return (Criteria) this;
        }

        public Criteria andBuyNotIn(List<String> values) {
            addCriterion("buy not in", values, "buy");
            return (Criteria) this;
        }

        public Criteria andBuyBetween(String value1, String value2) {
            addCriterion("buy between", value1, value2, "buy");
            return (Criteria) this;
        }

        public Criteria andBuyNotBetween(String value1, String value2) {
            addCriterion("buy not between", value1, value2, "buy");
            return (Criteria) this;
        }

        public Criteria andReligionIsNull() {
            addCriterion("religion is null");
            return (Criteria) this;
        }

        public Criteria andReligionIsNotNull() {
            addCriterion("religion is not null");
            return (Criteria) this;
        }

        public Criteria andReligionEqualTo(String value) {
            addCriterion("religion =", value, "religion");
            return (Criteria) this;
        }

        public Criteria andReligionNotEqualTo(String value) {
            addCriterion("religion <>", value, "religion");
            return (Criteria) this;
        }

        public Criteria andReligionGreaterThan(String value) {
            addCriterion("religion >", value, "religion");
            return (Criteria) this;
        }

        public Criteria andReligionGreaterThanOrEqualTo(String value) {
            addCriterion("religion >=", value, "religion");
            return (Criteria) this;
        }

        public Criteria andReligionLessThan(String value) {
            addCriterion("religion <", value, "religion");
            return (Criteria) this;
        }

        public Criteria andReligionLessThanOrEqualTo(String value) {
            addCriterion("religion <=", value, "religion");
            return (Criteria) this;
        }

        public Criteria andReligionLike(String value) {
            addCriterion("religion like", value, "religion");
            return (Criteria) this;
        }

        public Criteria andReligionNotLike(String value) {
            addCriterion("religion not like", value, "religion");
            return (Criteria) this;
        }

        public Criteria andReligionIn(List<String> values) {
            addCriterion("religion in", values, "religion");
            return (Criteria) this;
        }

        public Criteria andReligionNotIn(List<String> values) {
            addCriterion("religion not in", values, "religion");
            return (Criteria) this;
        }

        public Criteria andReligionBetween(String value1, String value2) {
            addCriterion("religion between", value1, value2, "religion");
            return (Criteria) this;
        }

        public Criteria andReligionNotBetween(String value1, String value2) {
            addCriterion("religion not between", value1, value2, "religion");
            return (Criteria) this;
        }

        public Criteria andTimeIsNull() {
            addCriterion("time is null");
            return (Criteria) this;
        }

        public Criteria andTimeIsNotNull() {
            addCriterion("time is not null");
            return (Criteria) this;
        }

        public Criteria andTimeEqualTo(String value) {
            addCriterion("time =", value, "time");
            return (Criteria) this;
        }

        public Criteria andTimeNotEqualTo(String value) {
            addCriterion("time <>", value, "time");
            return (Criteria) this;
        }

        public Criteria andTimeGreaterThan(String value) {
            addCriterion("time >", value, "time");
            return (Criteria) this;
        }

        public Criteria andTimeGreaterThanOrEqualTo(String value) {
            addCriterion("time >=", value, "time");
            return (Criteria) this;
        }

        public Criteria andTimeLessThan(String value) {
            addCriterion("time <", value, "time");
            return (Criteria) this;
        }

        public Criteria andTimeLessThanOrEqualTo(String value) {
            addCriterion("time <=", value, "time");
            return (Criteria) this;
        }

        public Criteria andTimeLike(String value) {
            addCriterion("time like", value, "time");
            return (Criteria) this;
        }

        public Criteria andTimeNotLike(String value) {
            addCriterion("time not like", value, "time");
            return (Criteria) this;
        }

        public Criteria andTimeIn(List<String> values) {
            addCriterion("time in", values, "time");
            return (Criteria) this;
        }

        public Criteria andTimeNotIn(List<String> values) {
            addCriterion("time not in", values, "time");
            return (Criteria) this;
        }

        public Criteria andTimeBetween(String value1, String value2) {
            addCriterion("time between", value1, value2, "time");
            return (Criteria) this;
        }

        public Criteria andTimeNotBetween(String value1, String value2) {
            addCriterion("time not between", value1, value2, "time");
            return (Criteria) this;
        }

        public Criteria andPetIsNull() {
            addCriterion("pet is null");
            return (Criteria) this;
        }

        public Criteria andPetIsNotNull() {
            addCriterion("pet is not null");
            return (Criteria) this;
        }

        public Criteria andPetEqualTo(String value) {
            addCriterion("pet =", value, "pet");
            return (Criteria) this;
        }

        public Criteria andPetNotEqualTo(String value) {
            addCriterion("pet <>", value, "pet");
            return (Criteria) this;
        }

        public Criteria andPetGreaterThan(String value) {
            addCriterion("pet >", value, "pet");
            return (Criteria) this;
        }

        public Criteria andPetGreaterThanOrEqualTo(String value) {
            addCriterion("pet >=", value, "pet");
            return (Criteria) this;
        }

        public Criteria andPetLessThan(String value) {
            addCriterion("pet <", value, "pet");
            return (Criteria) this;
        }

        public Criteria andPetLessThanOrEqualTo(String value) {
            addCriterion("pet <=", value, "pet");
            return (Criteria) this;
        }

        public Criteria andPetLike(String value) {
            addCriterion("pet like", value, "pet");
            return (Criteria) this;
        }

        public Criteria andPetNotLike(String value) {
            addCriterion("pet not like", value, "pet");
            return (Criteria) this;
        }

        public Criteria andPetIn(List<String> values) {
            addCriterion("pet in", values, "pet");
            return (Criteria) this;
        }

        public Criteria andPetNotIn(List<String> values) {
            addCriterion("pet not in", values, "pet");
            return (Criteria) this;
        }

        public Criteria andPetBetween(String value1, String value2) {
            addCriterion("pet between", value1, value2, "pet");
            return (Criteria) this;
        }

        public Criteria andPetNotBetween(String value1, String value2) {
            addCriterion("pet not between", value1, value2, "pet");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table shenghuofanngshi
     *
     * @mbg.generated do_not_delete_during_merge Tue Aug 11 10:35:40 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table shenghuofanngshi
     *
     * @mbg.generated Tue Aug 11 10:35:40 CST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}