package cn.kgc.xiangqin.entity;

public class ShengHuo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shenghuofanngshi.id
     *
     * @mbg.generated Tue Aug 11 10:35:40 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shenghuofanngshi.xiyan
     *
     * @mbg.generated Tue Aug 11 10:35:40 CST 2020
     */
    private String xiyan;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shenghuofanngshi.yinjiu
     *
     * @mbg.generated Tue Aug 11 10:35:40 CST 2020
     */
    private String yinjiu;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shenghuofanngshi.jianshen
     *
     * @mbg.generated Tue Aug 11 10:35:40 CST 2020
     */
    private String jianshen;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shenghuofanngshi.eat
     *
     * @mbg.generated Tue Aug 11 10:35:40 CST 2020
     */
    private String eat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shenghuofanngshi.buy
     *
     * @mbg.generated Tue Aug 11 10:35:40 CST 2020
     */
    private String buy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shenghuofanngshi.religion
     *
     * @mbg.generated Tue Aug 11 10:35:40 CST 2020
     */
    private String religion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shenghuofanngshi.time
     *
     * @mbg.generated Tue Aug 11 10:35:40 CST 2020
     */
    private String time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shenghuofanngshi.pet
     *
     * @mbg.generated Tue Aug 11 10:35:40 CST 2020
     */
    private String pet;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shenghuofanngshi.id
     *
     * @return the value of shenghuofanngshi.id
     *
     * @mbg.generated Tue Aug 11 10:35:40 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shenghuofanngshi.id
     *
     * @param id the value for shenghuofanngshi.id
     *
     * @mbg.generated Tue Aug 11 10:35:40 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shenghuofanngshi.xiyan
     *
     * @return the value of shenghuofanngshi.xiyan
     *
     * @mbg.generated Tue Aug 11 10:35:40 CST 2020
     */
    public String getXiyan() {
        return xiyan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shenghuofanngshi.xiyan
     *
     * @param xiyan the value for shenghuofanngshi.xiyan
     *
     * @mbg.generated Tue Aug 11 10:35:40 CST 2020
     */
    public void setXiyan(String xiyan) {
        this.xiyan = xiyan == null ? null : xiyan.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shenghuofanngshi.yinjiu
     *
     * @return the value of shenghuofanngshi.yinjiu
     *
     * @mbg.generated Tue Aug 11 10:35:40 CST 2020
     */
    public String getYinjiu() {
        return yinjiu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shenghuofanngshi.yinjiu
     *
     * @param yinjiu the value for shenghuofanngshi.yinjiu
     *
     * @mbg.generated Tue Aug 11 10:35:40 CST 2020
     */
    public void setYinjiu(String yinjiu) {
        this.yinjiu = yinjiu == null ? null : yinjiu.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shenghuofanngshi.jianshen
     *
     * @return the value of shenghuofanngshi.jianshen
     *
     * @mbg.generated Tue Aug 11 10:35:40 CST 2020
     */
    public String getJianshen() {
        return jianshen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shenghuofanngshi.jianshen
     *
     * @param jianshen the value for shenghuofanngshi.jianshen
     *
     * @mbg.generated Tue Aug 11 10:35:40 CST 2020
     */
    public void setJianshen(String jianshen) {
        this.jianshen = jianshen == null ? null : jianshen.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shenghuofanngshi.eat
     *
     * @return the value of shenghuofanngshi.eat
     *
     * @mbg.generated Tue Aug 11 10:35:40 CST 2020
     */
    public String getEat() {
        return eat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shenghuofanngshi.eat
     *
     * @param eat the value for shenghuofanngshi.eat
     *
     * @mbg.generated Tue Aug 11 10:35:40 CST 2020
     */
    public void setEat(String eat) {
        this.eat = eat == null ? null : eat.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shenghuofanngshi.buy
     *
     * @return the value of shenghuofanngshi.buy
     *
     * @mbg.generated Tue Aug 11 10:35:40 CST 2020
     */
    public String getBuy() {
        return buy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shenghuofanngshi.buy
     *
     * @param buy the value for shenghuofanngshi.buy
     *
     * @mbg.generated Tue Aug 11 10:35:40 CST 2020
     */
    public void setBuy(String buy) {
        this.buy = buy == null ? null : buy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shenghuofanngshi.religion
     *
     * @return the value of shenghuofanngshi.religion
     *
     * @mbg.generated Tue Aug 11 10:35:40 CST 2020
     */
    public String getReligion() {
        return religion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shenghuofanngshi.religion
     *
     * @param religion the value for shenghuofanngshi.religion
     *
     * @mbg.generated Tue Aug 11 10:35:40 CST 2020
     */
    public void setReligion(String religion) {
        this.religion = religion == null ? null : religion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shenghuofanngshi.time
     *
     * @return the value of shenghuofanngshi.time
     *
     * @mbg.generated Tue Aug 11 10:35:40 CST 2020
     */
    public String getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shenghuofanngshi.time
     *
     * @param time the value for shenghuofanngshi.time
     *
     * @mbg.generated Tue Aug 11 10:35:40 CST 2020
     */
    public void setTime(String time) {
        this.time = time == null ? null : time.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shenghuofanngshi.pet
     *
     * @return the value of shenghuofanngshi.pet
     *
     * @mbg.generated Tue Aug 11 10:35:40 CST 2020
     */
    public String getPet() {
        return pet;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shenghuofanngshi.pet
     *
     * @param pet the value for shenghuofanngshi.pet
     *
     * @mbg.generated Tue Aug 11 10:35:40 CST 2020
     */
    public void setPet(String pet) {
        this.pet = pet == null ? null : pet.trim();
    }
}