package cn.kgc.xiangqin.entity;

public class UserPass {


    private  YongHu yongHu;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_pass.uName
     *
     * @mbg.generated Sat Aug 08 15:49:35 CST 2020
     */
    private String uname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_pass.uid
     *
     * @mbg.generated Sat Aug 08 15:49:35 CST 2020
     */
    private Integer uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_pass.uPassword
     *
     * @mbg.generated Sat Aug 08 15:49:35 CST 2020
     */
    private String upassword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_pass.admin
     *
     * @mbg.generated Sat Aug 08 15:49:35 CST 2020
     */
    private Integer admin;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_pass.uName
     *
     * @return the value of user_pass.uName
     *
     * @mbg.generated Sat Aug 08 15:49:35 CST 2020
     */
    public String getUname() {
        return uname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_pass.uName
     *
     * @param uname the value for user_pass.uName
     *
     * @mbg.generated Sat Aug 08 15:49:35 CST 2020
     */
    public void setUname(String uname) {
        this.uname = uname == null ? null : uname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_pass.uid
     *
     * @return the value of user_pass.uid
     *
     * @mbg.generated Sat Aug 08 15:49:35 CST 2020
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_pass.uid
     *
     * @param uid the value for user_pass.uid
     *
     * @mbg.generated Sat Aug 08 15:49:35 CST 2020
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_pass.uPassword
     *
     * @return the value of user_pass.uPassword
     *
     * @mbg.generated Sat Aug 08 15:49:35 CST 2020
     */
    public String getUpassword() {
        return upassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_pass.uPassword
     *
     * @param upassword the value for user_pass.uPassword
     *
     * @mbg.generated Sat Aug 08 15:49:35 CST 2020
     */
    public void setUpassword(String upassword) {
        this.upassword = upassword == null ? null : upassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_pass.admin
     *
     * @return the value of user_pass.admin
     *
     * @mbg.generated Sat Aug 08 15:49:35 CST 2020
     */
    public Integer getAdmin() {
        return admin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_pass.admin
     *
     * @param admin the value for user_pass.admin
     *
     * @mbg.generated Sat Aug 08 15:49:35 CST 2020
     */
    public void setAdmin(Integer admin) {
        this.admin = admin;
    }


    @Override
    public String toString() {
        return "UserPass{" +
                "yongHu=" + yongHu +
                ", uname='" + uname + '\'' +
                ", uid=" + uid +
                ", upassword='" + upassword + '\'' +
                ", admin=" + admin +
                '}';
    }

    public UserPass() {
    }

    public UserPass(YongHu yongHu, String uname, Integer uid, String upassword, Integer admin) {
        this.yongHu = yongHu;
        this.uname = uname;
        this.uid = uid;
        this.upassword = upassword;
        this.admin = admin;
    }

    public YongHu getYongHu() {
        return yongHu;
    }

    public void setYongHu(YongHu yongHu) {
        this.yongHu = yongHu;
    }
}