package cn.kgc.xiangqin.entity;

import java.util.Date;

public class Vip {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip.v_id
     *
     * @mbg.generated Tue Aug 11 10:38:32 CST 2020
     */
    private Integer vId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip.v_start
     *
     * @mbg.generated Tue Aug 11 10:38:32 CST 2020
     */
    private Date vStart;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip.v_end
     *
     * @mbg.generated Tue Aug 11 10:38:32 CST 2020
     */
    private Date vEnd;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip.v_id
     *
     * @return the value of vip.v_id
     *
     * @mbg.generated Tue Aug 11 10:38:32 CST 2020
     */
    public Integer getvId() {
        return vId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip.v_id
     *
     * @param vId the value for vip.v_id
     *
     * @mbg.generated Tue Aug 11 10:38:32 CST 2020
     */
    public void setvId(Integer vId) {
        this.vId = vId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip.v_start
     *
     * @return the value of vip.v_start
     *
     * @mbg.generated Tue Aug 11 10:38:32 CST 2020
     */
    public Date getvStart() {
        return vStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip.v_start
     *
     * @param vStart the value for vip.v_start
     *
     * @mbg.generated Tue Aug 11 10:38:32 CST 2020
     */
    public void setvStart(Date vStart) {
        this.vStart = vStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip.v_end
     *
     * @return the value of vip.v_end
     *
     * @mbg.generated Tue Aug 11 10:38:32 CST 2020
     */
    public Date getvEnd() {
        return vEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip.v_end
     *
     * @param vEnd the value for vip.v_end
     *
     * @mbg.generated Tue Aug 11 10:38:32 CST 2020
     */
    public void setvEnd(Date vEnd) {
        this.vEnd = vEnd;
    }

    @Override
    public String toString() {
        return "Vip{" +
                "vId=" + vId +
                ", vStart=" + vStart +
                ", vEnd=" + vEnd +
                '}';
    }

    public Vip() {
    }

    public Vip(Integer vId, Date vStart, Date vEnd) {
        this.vId = vId;
        this.vStart = vStart;
        this.vEnd = vEnd;
    }
}