package cn.kgc.xiangqin.entity;

public class Work {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work.id
     *
     * @mbg.generated Tue Aug 11 17:05:51 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work.position
     *
     * @mbg.generated Tue Aug 11 17:05:51 CST 2020
     */
    private String position;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work.company
     *
     * @mbg.generated Tue Aug 11 17:05:51 CST 2020
     */
    private String company;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work.graduate
     *
     * @mbg.generated Tue Aug 11 17:05:51 CST 2020
     */
    private String graduate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work.major
     *
     * @mbg.generated Tue Aug 11 17:05:51 CST 2020
     */
    private String major;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work.income
     *
     * @mbg.generated Tue Aug 11 17:05:51 CST 2020
     */
    private String income;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work.house
     *
     * @mbg.generated Tue Aug 11 17:05:51 CST 2020
     */
    private String house;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work.buy
     *
     * @mbg.generated Tue Aug 11 17:05:51 CST 2020
     */
    private String buy;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work.id
     *
     * @return the value of work.id
     *
     * @mbg.generated Tue Aug 11 17:05:51 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work.id
     *
     * @param id the value for work.id
     *
     * @mbg.generated Tue Aug 11 17:05:51 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work.position
     *
     * @return the value of work.position
     *
     * @mbg.generated Tue Aug 11 17:05:51 CST 2020
     */
    public String getPosition() {
        return position;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work.position
     *
     * @param position the value for work.position
     *
     * @mbg.generated Tue Aug 11 17:05:51 CST 2020
     */
    public void setPosition(String position) {
        this.position = position == null ? null : position.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work.company
     *
     * @return the value of work.company
     *
     * @mbg.generated Tue Aug 11 17:05:51 CST 2020
     */
    public String getCompany() {
        return company;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work.company
     *
     * @param company the value for work.company
     *
     * @mbg.generated Tue Aug 11 17:05:51 CST 2020
     */
    public void setCompany(String company) {
        this.company = company == null ? null : company.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work.graduate
     *
     * @return the value of work.graduate
     *
     * @mbg.generated Tue Aug 11 17:05:51 CST 2020
     */
    public String getGraduate() {
        return graduate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work.graduate
     *
     * @param graduate the value for work.graduate
     *
     * @mbg.generated Tue Aug 11 17:05:51 CST 2020
     */
    public void setGraduate(String graduate) {
        this.graduate = graduate == null ? null : graduate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work.major
     *
     * @return the value of work.major
     *
     * @mbg.generated Tue Aug 11 17:05:51 CST 2020
     */
    public String getMajor() {
        return major;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work.major
     *
     * @param major the value for work.major
     *
     * @mbg.generated Tue Aug 11 17:05:51 CST 2020
     */
    public void setMajor(String major) {
        this.major = major == null ? null : major.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work.income
     *
     * @return the value of work.income
     *
     * @mbg.generated Tue Aug 11 17:05:51 CST 2020
     */
    public String getIncome() {
        return income;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work.income
     *
     * @param income the value for work.income
     *
     * @mbg.generated Tue Aug 11 17:05:51 CST 2020
     */
    public void setIncome(String income) {
        this.income = income == null ? null : income.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work.house
     *
     * @return the value of work.house
     *
     * @mbg.generated Tue Aug 11 17:05:51 CST 2020
     */
    public String getHouse() {
        return house;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work.house
     *
     * @param house the value for work.house
     *
     * @mbg.generated Tue Aug 11 17:05:51 CST 2020
     */
    public void setHouse(String house) {
        this.house = house == null ? null : house.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work.buy
     *
     * @return the value of work.buy
     *
     * @mbg.generated Tue Aug 11 17:05:51 CST 2020
     */
    public String getBuy() {
        return buy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work.buy
     *
     * @param buy the value for work.buy
     *
     * @mbg.generated Tue Aug 11 17:05:51 CST 2020
     */
    public void setBuy(String buy) {
        this.buy = buy == null ? null : buy.trim();
    }

    @Override
    public String toString() {
        return "Work{" +
                "id=" + id +
                ", position='" + position + '\'' +
                ", company='" + company + '\'' +
                ", graduate='" + graduate + '\'' +
                ", major='" + major + '\'' +
                ", income='" + income + '\'' +
                ", house='" + house + '\'' +
                ", buy='" + buy + '\'' +
                '}';
    }

    public Work() {
    }

    public Work(Integer id, String position, String company, String graduate, String major, String income, String house, String buy) {
        this.id = id;
        this.position = position;
        this.company = company;
        this.graduate = graduate;
        this.major = major;
        this.income = income;
        this.house = house;
        this.buy = buy;
    }
}