package cn.kgc.xiangqin.entity;

import java.util.ArrayList;
import java.util.List;

public class WorkExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table work
     *
     * @mbg.generated Tue Aug 11 10:39:04 CST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table work
     *
     * @mbg.generated Tue Aug 11 10:39:04 CST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table work
     *
     * @mbg.generated Tue Aug 11 10:39:04 CST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work
     *
     * @mbg.generated Tue Aug 11 10:39:04 CST 2020
     */
    public WorkExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work
     *
     * @mbg.generated Tue Aug 11 10:39:04 CST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work
     *
     * @mbg.generated Tue Aug 11 10:39:04 CST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work
     *
     * @mbg.generated Tue Aug 11 10:39:04 CST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work
     *
     * @mbg.generated Tue Aug 11 10:39:04 CST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work
     *
     * @mbg.generated Tue Aug 11 10:39:04 CST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work
     *
     * @mbg.generated Tue Aug 11 10:39:04 CST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work
     *
     * @mbg.generated Tue Aug 11 10:39:04 CST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work
     *
     * @mbg.generated Tue Aug 11 10:39:04 CST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work
     *
     * @mbg.generated Tue Aug 11 10:39:04 CST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work
     *
     * @mbg.generated Tue Aug 11 10:39:04 CST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table work
     *
     * @mbg.generated Tue Aug 11 10:39:04 CST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andZhiweiIsNull() {
            addCriterion("zhiwei is null");
            return (Criteria) this;
        }

        public Criteria andZhiweiIsNotNull() {
            addCriterion("zhiwei is not null");
            return (Criteria) this;
        }

        public Criteria andZhiweiEqualTo(String value) {
            addCriterion("zhiwei =", value, "zhiwei");
            return (Criteria) this;
        }

        public Criteria andZhiweiNotEqualTo(String value) {
            addCriterion("zhiwei <>", value, "zhiwei");
            return (Criteria) this;
        }

        public Criteria andZhiweiGreaterThan(String value) {
            addCriterion("zhiwei >", value, "zhiwei");
            return (Criteria) this;
        }

        public Criteria andZhiweiGreaterThanOrEqualTo(String value) {
            addCriterion("zhiwei >=", value, "zhiwei");
            return (Criteria) this;
        }

        public Criteria andZhiweiLessThan(String value) {
            addCriterion("zhiwei <", value, "zhiwei");
            return (Criteria) this;
        }

        public Criteria andZhiweiLessThanOrEqualTo(String value) {
            addCriterion("zhiwei <=", value, "zhiwei");
            return (Criteria) this;
        }

        public Criteria andZhiweiLike(String value) {
            addCriterion("zhiwei like", value, "zhiwei");
            return (Criteria) this;
        }

        public Criteria andZhiweiNotLike(String value) {
            addCriterion("zhiwei not like", value, "zhiwei");
            return (Criteria) this;
        }

        public Criteria andZhiweiIn(List<String> values) {
            addCriterion("zhiwei in", values, "zhiwei");
            return (Criteria) this;
        }

        public Criteria andZhiweiNotIn(List<String> values) {
            addCriterion("zhiwei not in", values, "zhiwei");
            return (Criteria) this;
        }

        public Criteria andZhiweiBetween(String value1, String value2) {
            addCriterion("zhiwei between", value1, value2, "zhiwei");
            return (Criteria) this;
        }

        public Criteria andZhiweiNotBetween(String value1, String value2) {
            addCriterion("zhiwei not between", value1, value2, "zhiwei");
            return (Criteria) this;
        }

        public Criteria andGongsiIsNull() {
            addCriterion("gongsi is null");
            return (Criteria) this;
        }

        public Criteria andGongsiIsNotNull() {
            addCriterion("gongsi is not null");
            return (Criteria) this;
        }

        public Criteria andGongsiEqualTo(String value) {
            addCriterion("gongsi =", value, "gongsi");
            return (Criteria) this;
        }

        public Criteria andGongsiNotEqualTo(String value) {
            addCriterion("gongsi <>", value, "gongsi");
            return (Criteria) this;
        }

        public Criteria andGongsiGreaterThan(String value) {
            addCriterion("gongsi >", value, "gongsi");
            return (Criteria) this;
        }

        public Criteria andGongsiGreaterThanOrEqualTo(String value) {
            addCriterion("gongsi >=", value, "gongsi");
            return (Criteria) this;
        }

        public Criteria andGongsiLessThan(String value) {
            addCriterion("gongsi <", value, "gongsi");
            return (Criteria) this;
        }

        public Criteria andGongsiLessThanOrEqualTo(String value) {
            addCriterion("gongsi <=", value, "gongsi");
            return (Criteria) this;
        }

        public Criteria andGongsiLike(String value) {
            addCriterion("gongsi like", value, "gongsi");
            return (Criteria) this;
        }

        public Criteria andGongsiNotLike(String value) {
            addCriterion("gongsi not like", value, "gongsi");
            return (Criteria) this;
        }

        public Criteria andGongsiIn(List<String> values) {
            addCriterion("gongsi in", values, "gongsi");
            return (Criteria) this;
        }

        public Criteria andGongsiNotIn(List<String> values) {
            addCriterion("gongsi not in", values, "gongsi");
            return (Criteria) this;
        }

        public Criteria andGongsiBetween(String value1, String value2) {
            addCriterion("gongsi between", value1, value2, "gongsi");
            return (Criteria) this;
        }

        public Criteria andGongsiNotBetween(String value1, String value2) {
            addCriterion("gongsi not between", value1, value2, "gongsi");
            return (Criteria) this;
        }

        public Criteria andZhuanyeIsNull() {
            addCriterion("zhuanye is null");
            return (Criteria) this;
        }

        public Criteria andZhuanyeIsNotNull() {
            addCriterion("zhuanye is not null");
            return (Criteria) this;
        }

        public Criteria andZhuanyeEqualTo(String value) {
            addCriterion("zhuanye =", value, "zhuanye");
            return (Criteria) this;
        }

        public Criteria andZhuanyeNotEqualTo(String value) {
            addCriterion("zhuanye <>", value, "zhuanye");
            return (Criteria) this;
        }

        public Criteria andZhuanyeGreaterThan(String value) {
            addCriterion("zhuanye >", value, "zhuanye");
            return (Criteria) this;
        }

        public Criteria andZhuanyeGreaterThanOrEqualTo(String value) {
            addCriterion("zhuanye >=", value, "zhuanye");
            return (Criteria) this;
        }

        public Criteria andZhuanyeLessThan(String value) {
            addCriterion("zhuanye <", value, "zhuanye");
            return (Criteria) this;
        }

        public Criteria andZhuanyeLessThanOrEqualTo(String value) {
            addCriterion("zhuanye <=", value, "zhuanye");
            return (Criteria) this;
        }

        public Criteria andZhuanyeLike(String value) {
            addCriterion("zhuanye like", value, "zhuanye");
            return (Criteria) this;
        }

        public Criteria andZhuanyeNotLike(String value) {
            addCriterion("zhuanye not like", value, "zhuanye");
            return (Criteria) this;
        }

        public Criteria andZhuanyeIn(List<String> values) {
            addCriterion("zhuanye in", values, "zhuanye");
            return (Criteria) this;
        }

        public Criteria andZhuanyeNotIn(List<String> values) {
            addCriterion("zhuanye not in", values, "zhuanye");
            return (Criteria) this;
        }

        public Criteria andZhuanyeBetween(String value1, String value2) {
            addCriterion("zhuanye between", value1, value2, "zhuanye");
            return (Criteria) this;
        }

        public Criteria andZhuanyeNotBetween(String value1, String value2) {
            addCriterion("zhuanye not between", value1, value2, "zhuanye");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table work
     *
     * @mbg.generated do_not_delete_during_merge Tue Aug 11 10:39:04 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table work
     *
     * @mbg.generated Tue Aug 11 10:39:04 CST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}