package cn.kgc.xiangqin.entity;

public class Work {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work.id
     *
     * @mbg.generated Tue Aug 11 10:39:04 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work.zhiwei
     *
     * @mbg.generated Tue Aug 11 10:39:04 CST 2020
     */
    private String zhiwei;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work.gongsi
     *
     * @mbg.generated Tue Aug 11 10:39:04 CST 2020
     */
    private String gongsi;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work.zhuanye
     *
     * @mbg.generated Tue Aug 11 10:39:04 CST 2020
     */
    private String zhuanye;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work.id
     *
     * @return the value of work.id
     *
     * @mbg.generated Tue Aug 11 10:39:04 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work.id
     *
     * @param id the value for work.id
     *
     * @mbg.generated Tue Aug 11 10:39:04 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work.zhiwei
     *
     * @return the value of work.zhiwei
     *
     * @mbg.generated Tue Aug 11 10:39:04 CST 2020
     */
    public String getZhiwei() {
        return zhiwei;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work.zhiwei
     *
     * @param zhiwei the value for work.zhiwei
     *
     * @mbg.generated Tue Aug 11 10:39:04 CST 2020
     */
    public void setZhiwei(String zhiwei) {
        this.zhiwei = zhiwei == null ? null : zhiwei.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work.gongsi
     *
     * @return the value of work.gongsi
     *
     * @mbg.generated Tue Aug 11 10:39:04 CST 2020
     */
    public String getGongsi() {
        return gongsi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work.gongsi
     *
     * @param gongsi the value for work.gongsi
     *
     * @mbg.generated Tue Aug 11 10:39:04 CST 2020
     */
    public void setGongsi(String gongsi) {
        this.gongsi = gongsi == null ? null : gongsi.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work.zhuanye
     *
     * @return the value of work.zhuanye
     *
     * @mbg.generated Tue Aug 11 10:39:04 CST 2020
     */
    public String getZhuanye() {
        return zhuanye;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work.zhuanye
     *
     * @param zhuanye the value for work.zhuanye
     *
     * @mbg.generated Tue Aug 11 10:39:04 CST 2020
     */
    public void setZhuanye(String zhuanye) {
        this.zhuanye = zhuanye == null ? null : zhuanye.trim();
    }
}