package cn.kgc.xiangqin.entity;

/**
 * @author 小肥
 */
public class YongHu {
    private  UserPass userPass;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yonghu.id
     *
     * @mbg.generated Mon Aug 10 13:46:16 CST 2020
     */
    private  Integer yid;
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yonghu.name
     *
     * @mbg.generated Mon Aug 10 13:46:16 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yonghu.marry
     *
     * @mbg.generated Mon Aug 10 13:46:16 CST 2020
     */
    private String marry;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yonghu.heighet
     *
     * @mbg.generated Mon Aug 10 13:46:16 CST 2020
     */
    private Integer heighet;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yonghu.qq
     *
     * @mbg.generated Mon Aug 10 13:46:16 CST 2020
     */
    private String qq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yonghu.phone
     *
     * @mbg.generated Mon Aug 10 13:46:16 CST 2020
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yonghu.school
     *
     * @mbg.generated Mon Aug 10 13:46:16 CST 2020
     */
    private String school;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yonghu.work
     *
     * @mbg.generated Mon Aug 10 13:46:16 CST 2020
     */
    private String work;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yonghu.sex
     *
     * @mbg.generated Mon Aug 10 13:46:16 CST 2020
     */
    private String sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yonghu.age
     *
     * @mbg.generated Mon Aug 10 13:46:16 CST 2020
     */
    private Integer age;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yonghu.house
     *
     * @mbg.generated Mon Aug 10 13:46:16 CST 2020
     */
    private String house;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yonghu.add
     *
     * @mbg.generated Mon Aug 10 13:46:16 CST 2020
     */
    private String add;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yonghu.vip
     *
     * @mbg.generated Mon Aug 10 13:46:16 CST 2020
     */
    private Integer vip;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yonghu.img
     *
     * @mbg.generated Mon Aug 10 13:46:16 CST 2020
     */
    private String img;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yonghu.jieshao
     *
     * @mbg.generated Mon Aug 10 13:46:16 CST 2020
     */
    private String jieshao;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yonghu.id
     *
     * @return the value of yonghu.id
     *
     * @mbg.generated Mon Aug 10 13:46:16 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yonghu.id
     *
     * @param id the value for yonghu.id
     *
     * @mbg.generated Mon Aug 10 13:46:16 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yonghu.name
     *
     * @return the value of yonghu.name
     *
     * @mbg.generated Mon Aug 10 13:46:16 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yonghu.name
     *
     * @param name the value for yonghu.name
     *
     * @mbg.generated Mon Aug 10 13:46:16 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yonghu.marry
     *
     * @return the value of yonghu.marry
     *
     * @mbg.generated Mon Aug 10 13:46:16 CST 2020
     */
    public String getMarry() {
        return marry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yonghu.marry
     *
     * @param marry the value for yonghu.marry
     *
     * @mbg.generated Mon Aug 10 13:46:16 CST 2020
     */
    public void setMarry(String marry) {
        this.marry = marry == null ? null : marry.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yonghu.heighet
     *
     * @return the value of yonghu.heighet
     *
     * @mbg.generated Mon Aug 10 13:46:16 CST 2020
     */
    public Integer getHeighet() {
        return heighet;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yonghu.heighet
     *
     * @param heighet the value for yonghu.heighet
     *
     * @mbg.generated Mon Aug 10 13:46:16 CST 2020
     */
    public void setHeighet(Integer heighet) {
        this.heighet = heighet;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yonghu.qq
     *
     * @return the value of yonghu.qq
     *
     * @mbg.generated Mon Aug 10 13:46:16 CST 2020
     */
    public String getQq() {
        return qq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yonghu.qq
     *
     * @param qq the value for yonghu.qq
     *
     * @mbg.generated Mon Aug 10 13:46:16 CST 2020
     */
    public void setQq(String qq) {
        this.qq = qq == null ? null : qq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yonghu.phone
     *
     * @return the value of yonghu.phone
     *
     * @mbg.generated Mon Aug 10 13:46:16 CST 2020
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yonghu.phone
     *
     * @param phone the value for yonghu.phone
     *
     * @mbg.generated Mon Aug 10 13:46:16 CST 2020
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yonghu.school
     *
     * @return the value of yonghu.school
     *
     * @mbg.generated Mon Aug 10 13:46:16 CST 2020
     */
    public String getSchool() {
        return school;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yonghu.school
     *
     * @param school the value for yonghu.school
     *
     * @mbg.generated Mon Aug 10 13:46:16 CST 2020
     */
    public void setSchool(String school) {
        this.school = school == null ? null : school.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yonghu.work
     *
     * @return the value of yonghu.work
     *
     * @mbg.generated Mon Aug 10 13:46:16 CST 2020
     */
    public String getWork() {
        return work;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yonghu.work
     *
     * @param work the value for yonghu.work
     *
     * @mbg.generated Mon Aug 10 13:46:16 CST 2020
     */
    public void setWork(String work) {
        this.work = work == null ? null : work.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yonghu.sex
     *
     * @return the value of yonghu.sex
     *
     * @mbg.generated Mon Aug 10 13:46:16 CST 2020
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yonghu.sex
     *
     * @param sex the value for yonghu.sex
     *
     * @mbg.generated Mon Aug 10 13:46:16 CST 2020
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yonghu.age
     *
     * @return the value of yonghu.age
     *
     * @mbg.generated Mon Aug 10 13:46:16 CST 2020
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yonghu.age
     *
     * @param age the value for yonghu.age
     *
     * @mbg.generated Mon Aug 10 13:46:16 CST 2020
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yonghu.house
     *
     * @return the value of yonghu.house
     *
     * @mbg.generated Mon Aug 10 13:46:16 CST 2020
     */
    public String getHouse() {
        return house;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yonghu.house
     *
     * @param house the value for yonghu.house
     *
     * @mbg.generated Mon Aug 10 13:46:16 CST 2020
     */
    public void setHouse(String house) {
        this.house = house == null ? null : house.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yonghu.add
     *
     * @return the value of yonghu.add
     *
     * @mbg.generated Mon Aug 10 13:46:16 CST 2020
     */
    public String getAdd() {
        return add;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yonghu.add
     *
     * @param add the value for yonghu.add
     *
     * @mbg.generated Mon Aug 10 13:46:16 CST 2020
     */
    public void setAdd(String add) {
        this.add = add == null ? null : add.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yonghu.vip
     *
     * @return the value of yonghu.vip
     *
     * @mbg.generated Mon Aug 10 13:46:16 CST 2020
     */
    public Integer getVip() {
        return vip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yonghu.vip
     *
     * @param vip the value for yonghu.vip
     *
     * @mbg.generated Mon Aug 10 13:46:16 CST 2020
     */
    public void setVip(Integer vip) {
        this.vip = vip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yonghu.img
     *
     * @return the value of yonghu.img
     *
     * @mbg.generated Mon Aug 10 13:46:16 CST 2020
     */
    public String getImg() {
        return img;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yonghu.img
     *
     * @param img the value for yonghu.img
     *
     * @mbg.generated Mon Aug 10 13:46:16 CST 2020
     */
    public void setImg(String img) {
        this.img = img == null ? null : img.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yonghu.jieshao
     *
     * @return the value of yonghu.jieshao
     *
     * @mbg.generated Mon Aug 10 13:46:16 CST 2020
     */
    public String getJieshao() {
        return jieshao;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yonghu.jieshao
     *
     * @param jieshao the value for yonghu.jieshao
     *
     * @mbg.generated Mon Aug 10 13:46:16 CST 2020
     */
    public void setJieshao(String jieshao) {
        this.jieshao = jieshao == null ? null : jieshao.trim();
    }

    public Integer getYid() {
        return yid;
    }

    public void setYid(Integer yid) {
        this.yid = yid;
    }

    public UserPass getUserPass() {
        return userPass;
    }

    public void setUserPass(UserPass userPass) {
        this.userPass = userPass;
    }


    @Override
    public String toString() {
        return "YongHu{" +
                "userPass=" + userPass +
                ", yid=" + yid +
                ", id=" + id +
                ", name='" + name + '\'' +
                ", marry='" + marry + '\'' +
                ", heighet=" + heighet +
                ", qq='" + qq + '\'' +
                ", phone='" + phone + '\'' +
                ", school='" + school + '\'' +
                ", work='" + work + '\'' +
                ", sex='" + sex + '\'' +
                ", age=" + age +
                ", house='" + house + '\'' +
                ", add='" + add + '\'' +
                ", vip=" + vip +
                ", img='" + img + '\'' +
                ", jieshao='" + jieshao + '\'' +
                '}';
    }

    public YongHu() {
    }

    public YongHu(UserPass userPass, Integer yid, Integer id, String name, String marry, Integer heighet, String qq, String phone, String school, String work, String sex, Integer age, String house, String add, Integer vip, String img, String jieshao) {
        this.userPass = userPass;
        this.yid = yid;
        this.id = id;
        this.name = name;
        this.marry = marry;
        this.heighet = heighet;
        this.qq = qq;
        this.phone = phone;
        this.school = school;
        this.work = work;
        this.sex = sex;
        this.age = age;
        this.house = house;
        this.add = add;
        this.vip = vip;
        this.img = img;
        this.jieshao = jieshao;
    }
}