package cn.kgc.xiangqin.mapper;

import cn.kgc.xiangqin.entity.Vip;
import cn.kgc.xiangqin.entity.VipExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface VipMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip
     *
     * @mbg.generated Tue Aug 11 10:38:32 CST 2020
     */
    long countByExample(VipExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip
     *
     * @mbg.generated Tue Aug 11 10:38:32 CST 2020
     */
    int deleteByExample(VipExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip
     *
     * @mbg.generated Tue Aug 11 10:38:32 CST 2020
     */
    int deleteByPrimaryKey(Integer vId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip
     *
     * @mbg.generated Tue Aug 11 10:38:32 CST 2020
     */
    int insert(Vip record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip
     *
     * @mbg.generated Tue Aug 11 10:38:32 CST 2020
     */
    int insertSelective(Vip record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip
     *
     * @mbg.generated Tue Aug 11 10:38:32 CST 2020
     */
    List<Vip> selectByExample(VipExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip
     *
     * @mbg.generated Tue Aug 11 10:38:32 CST 2020
     */
    Vip selectByPrimaryKey(Integer vId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip
     *
     * @mbg.generated Tue Aug 11 10:38:32 CST 2020
     */
    int updateByExampleSelective(@Param("record") Vip record, @Param("example") VipExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip
     *
     * @mbg.generated Tue Aug 11 10:38:32 CST 2020
     */
    int updateByExample(@Param("record") Vip record, @Param("example") VipExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip
     *
     * @mbg.generated Tue Aug 11 10:38:32 CST 2020
     */
    int updateByPrimaryKeySelective(Vip record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip
     *
     * @mbg.generated Tue Aug 11 10:38:32 CST 2020
     */
    int updateByPrimaryKey(Vip record);
}